# 服务端口号
server:
  port: 8082

# spring服务器配置-名称
spring:
  application:
    name: department-service
    # 数据源配置链接
  datasource:
    # url是指数据库的连接地址
    url: jdbc:mysql://localhost:3306/medi_care_platform?useSSL=false&serverTimezone=UTC&characterEncoding=utf8mb4
    # username是指数据库的用户名
    username: root
    # password是指数据库的密码
    password: 123456
    # driver-class-name是指数据库的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver


    # jpa配置
  jpa:
    hibernate:
      # update是指数据库的DDL操作
      ddl-auto: update
      # show-sql是指是否显示SQL
    show-sql: true

  # nacos配置
  nacos:
    config:
      # nacos的配置中心地址
      server-addr: localhost:8848
      # nacos的命名空间
      namespace: public
      # nacos的配置文件名称
      group: DEFAULT_GROUP
    # nacos的注册中心配置
    discovery:
      server-addr: localhost:8848
      namespace: public